### ISSUE TITLE
The project status

### ISSUE THREAD

**Issue by nikita-volkov** [knowm/AHaH#1]
What is the current project status? It seems to be staled.

Also why is it not released thru Maven Central?

**Comment by timmolter** [comment]
This is just an archive of code referenced from our 2014 paper: [AHaH Computing–From Metastable Switches to Attractors to Machine Learning](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0085175).

**Comment by timmolter** [comment]
I updated the README.

**Comment by nikita-volkov** [comment]
Thanks for the prompt reaction!
